services:
  bias-boutique-app:
    build: .
    container_name: bias-boutique-app
    restart: on-failure
    ports:
      - "4000:4000"
    environment:
      - APP_DEBUG=${APP_DEBUG}
      - APP_API_KEY=${APP_API_KEY}
      - APP_DATABASE_DB=${APP_DATABASE_DB}
      - APP_XENDIT_SECRET_KEY=${APP_XENDIT_SECRET_KEY}
      - APP_XENDIT_PUBLIC_KEY=${APP_XENDIT_PUBLIC_KEY}
    volumes:
      - .:/app
